### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by MohdSabra** [hadenpf/bankboga#1]
it is probably a silly question but how do you run this code and see the fake bank?

**Comment by Tim-Hoare** [comment]
To run locally:

(Assuming you have node.js installed)

1. Clone the repo
2. npm install
3. npm start
4. Hit up localhost:8080

**Comment by janmarinka** [comment]
> To run locally:
> 
> (Assuming you have node.js installed)
> 
> 1. Clone the repo
> 2. npm install
> 3. npm start
> 4. Hit up localhost:8080

Hello, Im so sorry but I still dont understand this can you please help me? :(

**Comment by Tim-Hoare** [comment]
In order to run this, you need to have node.js, a javascript environment installed on your machine. Once you have done that, you need to need clone this repository (using git, or clicking on the 'clone or download' button on the main page). Then, you need to open up a terminal, and set your working directory to where your cloned the repository to and  follow steps 2 onwards from above.

**Comment by hadenpf** [comment]
Closed because instructions have been given by community. Thank you @Tim-Hoare!

**Comment by andreas-b89** [comment]
> Closed because instructions have been given by community. Thank you @Tim-Hoare!

hallo can you guide me how to run this code i have linux environment thanking you.
